namespace CinematographyPlugin.UI.Enums
{
    public enum UIOption
    {
        ToggleUI,
        ToggleBody,
        ToggleFreeCamera,
        MovementSpeedSlider,
        MovementSmoothingSlider,
        RotationSpeedSlider,
        RotationSmoothingSlider,
        ToggleDynamicRoll,
        DynamicRollIntensitySlider,
        ToggleMouseCtrlAltitude,
        ToggleLookSmoothing,
        LookSmoothingSlider,
        ToggleCameraRoll,
        CameraRollSlider,
        CameraRollSpeedSlider,
        CameraRollSmoothingSlider,
        ToggleTimeScale,
        TimeScaleSlider,
        ToggleFoV,
        FoVSlider,
        FoVSpeedSlider,
        FoVSmoothingSlider,
        ToggleVignette,
        ToggleDoF,
        FocusDistanceSlider,
        ApertureSlider,
        FocalLenghtSlider
    }
}