namespace CinematographyPlugin.UI.Enums
{
    public enum UIOption
    {
        ToggleUI,
        ToggleBio,
        ToggleAspectRatio,
        AspectRatioSlider,
        ToggleBody,
        ToggleFreeCamera,
        MovementSpeedSlider,
        MovementSmoothingSlider,
        RotationSpeedSlider,
        RotationSmoothingSlider,
        ZoomSpeedSlider,
        ZoomSmoothingSlider,
        ToggleDynamicRoll,
        DynamicRollIntensitySlider,
        ToggleAlignPitchAxisWCam,
        ToggleAlignRollAxisWCam,
        ToggleFpsLookSmoothing,
        FpsLookSmoothingSlider,
        ToggleDoF,
        FocusDistanceSlider,
        ApertureSlider,
        FocalLenghtSlider,
        ToggleVignette,
        ToggleAmbientParticles,
        ToggleTimeScale,
        TimeScaleSlider,
    }
}